---
abstract: unknown
author:
  - SayMedia
build_requires:
  Plack: 0
  Plack::Handler::Twiggy: 0
  Plack::Request: 0.99
  Test::More: 0
  Test::Requires: 0
  Test::TCP: 0
  YAML::Syck: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Peer39
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent::HTTP: 0
  Data::Validator: 0
  Mouse: 0
version: 0.32
